---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplateChain
metadata:
  name: core
  namespace: kcm-system
spec:
  supportedTemplates:
    - name: ca-1-0-6
    - name: edns-1-21-1
    - name: eso-2-8-0
    - name: gateway-1-0-3
    - name: gwapi-1-0-5
    - name: operator-1-0-3
