---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-3.7.1-tpl
spec:
  interval: 10m0s
  releaseName: monitoring-3.7.1-tpl
  chartRef:
    kind: HelmChart
    name: monitoring-3.7.1-tpl
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: monitoring-3.7.1-tpl
spec:
  interval: 10m0s
  chart: servicetemplate/monitoring-service-template
  version: 3.7.1
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: labsonline-catalog
