---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: addon
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      multi-cluster-service: addon
  dependsOn: []
  serviceSpec:
    priority: 100
    services: []
      # TODO: gatekeeper
      # - template: gatekeeper-3-23-0
      #   name: gatekeeper
      #   namespace: kube-system
      #   dependsOn: []
      #   values: ""
      # TODO: monitoring
      # - template: monitoring-4-3-1
      #   name: monitoring
      #   namespace: kube-system
      #   dependsOn: []
      #   values: ""
