---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: secret
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  dependsOn: []
  serviceSpec:
    priority: 100
    services:
      - template: eso-2-8-0
        name: external-secret
        namespace: sre
        # dependsOn:
        #   - name: external-secret-operator
        #     namespace: operators
        #   - name: vault
        #     namespace: sre
        values: |
          generators:
            - kind: ClusterGenerator
              name: pwdgen
              generator:
                passwordSpec:
                  length: 42
                  digits: 5
                  symbols: 5
                  symbolCharacters: -_$@
                  noUpper: false
                  allowRepeat: true
            - kind: ClusterGenerator
              name: uuidgen
              type: UUID
              generator:
                uuidSpec: {}
            - kind: ClusterGenerator
              name: sshkeygen
              type: SSHKey
              generator:
                sshKeySpec:
                  keyType: ed25519
          secretStores: []
            # - kind: ClusterSecretStore
            #   name: vault
            #   provider:
            #     vault:
            #       server: https://vault.sandbox.testplay.io
            #       namespace: sandbox
            #       path: secret
            #       version: v2
            #       checkAndSet:
            #         required: true
            #       auth:
            #         appRole:
            #           path: approle
            #           # FIXME: replace with the secret-id of the approle created in vault
            #           roleId: ""
            #           secretRef:
            #             name: external-secrets-vault-credential
            #             namespace: sre
            #             key: secret-id
          externalSecrets: []
            # - kind: ExternalSecret
            #   name: tsig-secret
            #   namespace: kcm-system
            #   externalSecretSpec:
            #     secretStoreRef:
            #       name: vault
            #       kind: ClusterSecretStore
            #     target:
            #       name: tsig-secret
            #     data:
            #       - secretKey: secret
            #         remoteRef:
            #           key: maas/tsig
            #           property: certmanager
            # - kind: ExternalSecret
            #   name: tsig-secret
            #   namespace: kube-system
            #   externalSecretSpec:
            #     secretStoreRef:
            #       name: vault
            #       kind: ClusterSecretStore
            #     target:
            #       name: tsig-secret
            #     data:
            #       - secretKey: secret
            #         remoteRef:
            #           key: maas/tsig
            #           property: externaldns
