---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: addon
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/addon: enabled
  serviceSpec:
    priority: 100
    services:
      # TODO: pinniped
      - template: pinniped-2-4-23
        name: pinniped
        namespace: kube-system
        values: ""
      # TODO: lgtm
      - template: monitoring-3.7.1
        name: lgtm
        namespace: sre
        values: ""
      # TODO: operator
      - template: operator-1-0-2
        name: operator
        namespace: sre
        values: ""
