---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: crd
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: external-snapshotter-crd
        name: external-snapshotter-crd
        namespace: kube-system
      - template: prometheus-operator-crd
        name: prometheus-operator-crd
        namespace: kube-system
