---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: global
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: ca-1-0-3
        name: ca
        namespace: cert-manager
        values: |

          issuers: []
          cert-manager:
            enabled: true
            enableCertificateOwnerRef: true
            podDnsPolicy: None
            crds:
              enabled: true
              keep: true
            config:
              enableGatewayAPI: true
            podDnsConfig:
              nameservers:
                - 1.1.1.1
      - template: ca-1-0-3
        name: ca-issuer
        namespace: cert-manager
        values: |

          issuers:
            - name: ca-issuer-self-signed
              clustered: true
              selfSigned: true
              secret:
                create: false
            - name: ca-issuer
              certManagerNamespace: cert-manager
              type: ca
              clustered: true
              secret:
                name: ca-issuer-cred
                create: false
                ca:
                  crt: null
                  key: null
          cert-manager:
            enabled: false
          trust-manager:
            enabled: false
      # - template: edns-1-19-0
      #   name: edns
      #   namespace: kube-system
      #   values: |

      #     endpoints: []
      #     # - name: examplearecord
      #     #   records:
      #     #     - name: example.com
      #     #       targets:
      #     #         - 10.0.0.1
      #     externaldns:
      #       enabled: true
      #       policy: sync
      #       txtOwnerId: {{ .Cluster.metadata.name }}  # FIXME: edns owner id
      #       txtPrefix: {{ .Cluster.metadata.name }}-  # FIXME: edns prefix
      #       logLevel: info
      #       interval: 30s
      #       triggerLoopOnEvent: true
      #       gatewayNamespace: kube-system
      #       # gatewayLabelFilter: external-dns=enabled
      #       # domainFilters: []
      #       sources:
      #         - crd
      #         - gateway-grpcroute
      #         - gateway-httproute
      #         - ingress
      #         - service
      #       provider:
      #         name: cloudflare
      #       env:
      #         - name: CF_API_TOKEN
      #           valueFrom:
      #             secretKeyRef:
      #               name: cloudflare-api-token
      #               key: cf-api-token
      # - template: gwapi-1-0-3
      #   name: gwapi
      #   namespace: kube-system
      #   values: |

      #     gwapi:
      #       config:
      #         envoyGateway:
      #           gateway:
      #             controllerName: gateway.envoyproxy.io/gatewayclass-controller
      #           provider:
      #             type: Kubernetes
      #           logging:
      #             level:
      #               default: info
      #       service:
      #         type: LoadBalancer
      #         annotations:
      #           external-dns.alpha.kubernetes.io/hostname: "" # TODO: gwapi domain
      #       topologyInjector:
      #         enabled: true
      # - template: gwapi-1-0-3
      #   name: gwclass
      #   namespace: kube-system
      #   values: |

      #     classes:
      #       - name: envoy
      #         description: "Default Envoy Gateway class"
      #     gwapi:
      #       enabled: false
      #       # config:
      #       #   envoyGateway:
      #       #     gateway:
      #       #       controllerName: gateway.envoyproxy.io/gatewayclass-controller
      # - template: gateway-1-0-3
      #   name: gateway
      #   namespace: kube-system
      #   values: |

      #     grants:
      #       - name: allow-gateways-to-ref-secrets
      #         to:
      #           - group: ""
      #             kind: Secret
      #         from:
      #           - group: gateway.networking.k8s.io
      #             kind: Gateway
      #             namespace: kube-system
      #     gateways:
      #       - name: http-gateway
      #         className: envoy
      #         listeners:
      #           - name: https
      #             port: 443
      #             protocol: HTTPS
      #             hostname: ""  # TODO: gwapi hostname & issuer
      #             allowedRoutes:
      #               namespaces:
      #                 from: All
      #             tls:
      #               mode: Terminate
      #               certificateRefs:
      #                 - name: http-gw-cert
      #                   issuer: ca-issuer-self-signed
      #       # - name: grpc-gateway
      #       #   className: envoy
      #       #   listeners:
      #       #     - name: grpc
      #       #       port: 443
      #       #       protocol: HTTPS
      #       #       hostname: ""  # TODO: gwapi hostname & issuer
      #       #       allowedRoutes:
      #       #         namespaces:
      #       #           from: All
      #       #         kinds:
      #       #           - kind: GRPCRoute
      #       #       tls:
      #       #         mode: Terminate
      #       #         certificateRefs:
      #       #           - name: grpc-gw-cert
      #       #             issuer: ca-issuer-self-signed
