---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-docker
  namespace: default
spec:
  dryRun: false
  template: docker-hosted-cp-1-0-4
  credential: docker-cluster-cred
  propagateCredentials: false
  config:
    # clusterLabels:
    #   app.kubernetes.io/knative: enabled
    #   app.kubernetes.io/addon: enabled
    k0smotron:
      service:
        type: NodePort
    # TODO: modify docker-hosted-cp to allow configuring k0s
    # k0s:
    #   api:
    #     sans:
    #       - docker.kubernetes.local
    #   network:
    #     provider: custom
    #   featureGates:
    #     - name: UserNamespacesSupport
    #       enabled: true
  serviceSpec:
    services: []
    # - template: cni-1-0-0
    #   name: cni
    #   namespace: kcm-system
