---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-openstack
  namespace: default
spec:
  # template: openstack-standalone-cp-1-0-21  # Enterprise
  # template: openstack-standalone-cp-1-0-22  # OSS
  credential: openstack-cluster-cred
  propagateCredentials: false
  config:
    controlPlaneNumber: 1
    # clusterLabels:
    #   app.kubernetes.io/knative: enabled
    #   app.kubernetes.io/addon: enabled
    # k0s:
    #   api:
    #     sans:
    #       - openstack.kubernetes.local
    #   network:
    #     provider: custom
    #   featureGates:
    #     - name: UserNamespacesSupport
    #       enabled: true
  serviceSpec:
    services: []
    # - template: cni-1-0-0
    #   name: cni
    #   namespace: kcm-system
