---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  name: kcm
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  release: k0rdent-enterprise-1-4-0
  core:
    capi: {}
    kcm:
      config:
        regional:
          cert-manager:
            config:
              enableGatewayAPI: true
  providers:
    - name: cluster-api-provider-aws
    - name: cluster-api-provider-azure
    - name: cluster-api-provider-docker
    - name: cluster-api-provider-gcp
    - name: cluster-api-provider-infoblox
    - name: cluster-api-provider-ipam
    - name: cluster-api-provider-k0sproject-k0smotron
    - name: cluster-api-provider-kubevirt
    - name: cluster-api-provider-openstack
    - name: cluster-api-provider-vsphere
    - name: projectsveltos
    - name: cluster-api-provider-maas
      template: cluster-api-provider-maas-0-9-0
      config:
        global:
          registry: ""
        # configSecret:
        #   create: false
        #   name: maas-variables
        #   namespace: kcm-system
        config:
          MAAS_ENDPOINT: http://maas.sandbox.testplay.io:5240/MAAS
        deployment:
          containers:
            - name: manager
              imageUrl: ghcr.io/labsonline/capi/cluster-api-provider-maas-controller:v1.0.0-arm64
