---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: cloudflare
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      multi-cluster-service: cloudflare
  dependsOn: []
  serviceSpec:
    priority: 100
    services:
      - template: eso-2-8-0
        name: cloudflare-external-secret
        namespace: sre
        # dependsOn:
        #   - name: external-secret-operator
        #     namespace: operators
        #   - name: external-secret
        #     namespace: sre
        values: |
          generators: []
          secretStores: []
          externalSecrets:
            - kind: ExternalSecret
              name: cloudflare-tunnel-token
              namespace: cloudflare-system
              externalSecretSpec:
                secretStoreRef:
                  name: vault
                  namespace: sre
                  kind: ClusterSecretStore
                target:
                  name: cloudflare-credentials
                data:
                  - secretKey: tunnel-token
                    remoteRef:
                      key: cloudflare/tunnel
                      property: tunnel-token
            - kind: ExternalSecret
              name: cloudflare-credentials
              namespace: cloudflare-system
              externalSecretSpec:
                secretStoreRef:
                  name: vault
                  namespace: sre
                  kind: ClusterSecretStore
                target:
                  name: cloudflare-credentials
                data:
                  - secretKey: api-token
                    remoteRef:
                      key: cloudflare/tunnel
                      property: api-token
            - kind: ExternalSecret
              name: cloudflare-api-key
              namespace: cloudflare-system
              externalSecretSpec:
                secretStoreRef:
                  name: vault
                  namespace: sre
                  kind: ClusterSecretStore
                target:
                  name: cloudflare-credentials
                data:
                  - secretKey: apiKey
                    remoteRef:
                      key: cloudflare/dns
                      property: token
            - kind: ExternalSecret
              name: ca-secret-cloudflare
              namespace: cert-manager
              externalSecretSpec:
                secretStoreRef:
                  name: vault
                  namespace: sre
                  kind: ClusterSecretStore
                target:
                  name: cloudflare-credentials
                data:
                  - secretKey: token
                    remoteRef:
                      key: cloudflare/dns
                      property: token
