---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-mcs
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  serviceSpec:
    priority: 100
    services: #[]
      # - template: external-snapshotter-crd
      #   name: external-snapshotter-crd
      #   namespace: kube-system
      - template: ca-1-0-2
        name: ca-issuer
        namespace: cert-manager
        values: |

          issuers:
            - name: ca-issuer-self-signed
              clustered: true
              selfSigned: true
              secret:
                create: false
            # TODO: ca-issuer
            # - name: ca-issuer
            #   certManagerNamespace: cert-manager
            #   type: ca
            #   clustered: true
            #   secret:
            #     name: ca-issuer-cred
            #     create: false
            #     ca:
            #       crt: null
            #       key: null
          cert-manager:
            enabled: false
          trust-manager:
            enabled: false
      # FIXME: edns provider
      # - template: edns-1-0-2
      #   name: edns
      #   namespace: kube-system
      #   values: |

      #     endpoints: []
      #     # - name: examplearecord
      #     #   records:
      #     #     - name: example.com
      #     #       targets:
      #     #         - 10.0.0.1
      #     external-dns:
      #       enabled: true
      #       policy: sync
      #       txtOwnerId: edns
      #       txtPrefix: edns-
      #       logLevel: info
      #       interval: 30s
      #       triggerLoopOnEvent: true
      #       gatewayNamespace: kube-system
      #       # gatewayLabelFilter: external-dns=enabled
      #       # domainFilters: []
      #       sources:
      #         - crd
      #         - gateway-grpcroute
      #         - gateway-httproute
      #         - service
      #         # - ingress
      #       # provider:
      #       #   name: cloudflare
      #       # env:
      #       #   - name: CF_API_TOKEN
      #       #     valueFrom:
      #       #       secretKeyRef:
      #       #         name: cloudflare-api-token
      #       #         key: cf-api-token
      # FIXME: gwapi hostname & issuer
      # - template: gateway-1-0-2
      #   name: gateway
      #   namespace: kube-system
      #   values: |

      #     grants:
      #       - name: allow-gateways-to-ref-secrets
      #         to:
      #           - group: ""
      #             kind: Secret
      #         from:
      #           - group: gateway.networking.k8s.io
      #             kind: Gateway
      #             namespace: kube-system
      #     gateways:
      #       - name: http-gateway
      #         className: envoy-gateway
      #         listeners:
      #           - name: https
      #             port: 443
      #             protocol: HTTPS
      #             hostname: "*.local"
      #             allowedRoutes:
      #               namespaces:
      #                 from: All
      #             tls:
      #               mode: Terminate
      #               certificateRefs:
      #                 - name: http-gw-cert
      #                   issuer: ca-issuer-self-signed
      #       - name: grpc-gateway
      #         className: envoy-gateway
      #         listeners:
      #           - name: grpc
      #             port: 443
      #             protocol: HTTPS
      #             hostname: "*.local"
      #             allowedRoutes:
      #               namespaces:
      #                 from: All
      #               kinds:
      #                 - kind: GRPCRoute
      #             tls:
      #               mode: Terminate
      #               certificateRefs:
      #                 - name: grpc-gw-cert
      #                   issuer: ca-issuer-self-signed
