---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: vsphere-cluster-cred
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereClusterIdentity
    name: vsphere-cluster-identity
    namespace: kcm-system
