---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-remote
  namespace: default
spec:
  # FIXME: change template to custom standalone cp
  template: remote-cluster-1-0-18 # Enterprise
  # template: remote-cluster-1-0-19 # OSS
  credential: remote-cluster-cred
  propagateCredentials: false
  config:
    controlPlaneNumber: 1
    # clusterLabels:
    #   app.kubernetes.io/knative: enabled
    #   app.kubernetes.io/addon: enabled
    # machines:
    #   - address: 127.0.0.1
    #     user: ubuntu # The user must have root permissions
    #     port: 22
    k0s:
      arch: amd64
      cpArgs: []
      workerArgs: []
      api:
        extraArgs: {}
      network:
        provider: custom
      extension:
        helm:
          charts:
            - name: cni
              chartname: oci://ghcr.io/labsonline/charts/cni
              namespace: kube-system
              version: 1.0.0
              values: |
                cilium:
                  kubeProxyReplacement: true
                  bgpControlPlane:
                    enabled: false
                  pool:
                    enabled: true
                    allowFirstLastIPs: No
                    cidr: 172.16.254.0/24
                  operator:
                    replicas: 1
            - name: csi
              chartname: oci://ghcr.io/labsonline/charts/csi
              namespace: kube-system
              version: 1.0.0
              values: |
                ceph:
                  enabled: false
                openebs:
                  csi:
                    volumeSnapshots:
                      enabled: true
                      keep: false
                  localpv-provisioner:
                    hostpathClass:
                      name: general
  serviceSpec:
    services: []
    # - template: openstack-1-0-0
    #   name: openstack
    #   namespace: kcm-system
