---
# FIXME: remove and replace with eso
apiVersion: v1
kind: Secret
metadata:
  name: maas-cluster-identity-secret
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: mhcp-cluster-cred
spec:
  identityRef:
    apiVersion: v1
    kind: Secret
    name: maas-cluster-identity-secret
    namespace: kcm-system
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: mhcp
spec:
  template: maas-standalone-cp-0-1-2
  credential: mhcp-cluster-cred
  dryRun: false
  config:
    # controlPlaneEndpointIP: ""
    controlPlaneNumber: 1
    workersNumber: 2
    # clusterAnnotations:
    #   domain: kcm.testplay.io
    # clusterLabels:
    #   app.kubernetes.io/knative: enabled
    #   app.kubernetes.io/addon: enabled
    controlPlane:
      image: ubuntu
      minCPU: 2
      minMemory: 8192
      resourcePool: ""
      tags: []
    worker:
      image: ubuntu
      minCPU: 2
      minMemory: 8192
      resourcePool: ""
      tags: []
    nameservers:
      - 10.20.0.1
      - 192.168.2.10
    maas:
      dnsDomain: kcm.testplay.io
    k0s:
      version: v1.35.4+k0s.0
      arch: arm64
      network:
        provider: custom
      api:
        extraArgs: {}
      cpArgs: []
      workerArgs: []
  serviceSpec:
    services:
      - name: cilium
        namespace: kube-system
        template: cni-1-0-7
        values: |
          # FIXME: cilium
          cilium:
            enabled: true
            kubeProxyReplacement: true
            # k8sServiceHost: 192.168.2.12
            k8sServicePort: 6443
            # ipv6:
            #   enabled: true
            operator:
              replicas: 1
            hubble:
              relay:
                enabled: true
              ui:
                enabled: true
            # nodePort:
            #   addresses:
            #     - 192.168.17.0/24
            #     # - fd00:192:168:17::0/64
            bpf:
              hostLegacyRouting: true
            # bgp:
            #   enabled: true
            #   peer:
            #     authSecretRef: ""
            #     addressFamilies:
            #       - afi: ipv4
            #         safi: unicast
            #         advertisements:
            #           matchLabels:
            #             advertise: bgp
            #       # - afi: ipv6
            #       #   safi: unicast
            #       #   advertisements:
            #       #     matchLabels:
            #       #       advertise: bgp
            #   instances:
            #     - name: frr
            #       localASN: 64512
            #       overrides:
            #         enabled: true
            #       peers:
            #         - name: frrv4
            #           peerASN: 64513
            #           peerAddress: 10.20.0.1
            #           peerConfigRef:
            #             name: bgp-peer-config
            #         # - name: frrv6
            #         #   peerASN: 64513
            #         #   peerAddress: fd00:10:20::1
            #         #   peerConfigRef:
            #         #     name: bgp-peer-config
            l2:
              enabled: true
              interfaces:
                - oam
            pool:
              enabled: true
              blocks:
                - start: 192.168.2.128
                  stop: 192.168.2.159
                # - cidr: 172.30.255.0/24
                # - cidr: fd00:ff::0/64
      - name: openebs
        namespace: kube-system
        template: csi-1-0-7
        # values: |
        #   openebs:
        #     openebs-crds:
        #       csi:
        #         volumeSnapshots:
        #           enabled: true
        #     lvm-localpv:
        #       lvmNode:
        #         kubeletDir: /var/lib/k0s/kubelet/
        #       class:
        #         volgroup: openebs-vg
        #     localpv-provisioner:
        #       hostpathClass:
        #         enabled: false
        #       localpv:
        #         enabled: false
        #     engines:
        #       local:
        #         lvm:
        #           enabled: true
