---
# FIXME: remove and replace with eso
apiVersion: v1
kind: Secret
metadata:
  name: mscp-base-userdata
  namespace: default
type: Opaque
stringData:
  value: |
    #cloud-config
    merge_how:
      - name: list
        settings: [append]
      - name: dict
        settings: [no_replace, recurse_list]
    package_update: true
    timezone: Etc/UTC
    keyboard:
      layout: us
    ntp:
      pools:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
        - 3.pool.ntp.org
    users:
      - default
      - name: rescue
        hashed_passwd: ""
        groups: adm, cdrom, sudo, dip, plugdev, lxd
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
      - name: admin
        primary_group: admin
        groups: adm, cdrom, sudo, dip, plugdev, lxd
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: true
        ssh_authorized_keys: []
    packages:
      - apparmor
      - apt-transport-https
      - ca-certificates
      - cloud-init
      - cron
      - curl
      - git
      - gnupg
      - gnupg-agent
      - libseccomp2
      - openssl
      - python3
      - software-properties-common
      - util-linux
      - vim
      - wget
    write_files:
      - path: /usr/local/share/ca-certificates/ca.crt
        permissions: "0644"
        owner: root
        content: ""
      - path: /usr/lib/systemd/system/user@.service.d/delegate.conf
        permissions: "0644"
        owner: root
        content: |
          [Service]
          Delegate=cpu cpuset io memory pids
      - path: /etc/environment
        permissions: "0644"
        owner: root
        content: |
          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          EDITOR="vim"
          PAGER="cat"
      - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        permissions: "0644"
        owner: root
        content: |
          network:
            config: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: maas-cluster-identity-secret
  namespace: default
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: mscp-cluster-cred
  namespace: default
spec:
  identityRef:
    apiVersion: v1
    kind: Secret
    name: maas-cluster-identity-secret
    namespace: default
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: mscp
  namespace: default
spec:
  template: maas-standalone-cp-0-1-3
  credential: mscp-cluster-cred
  dryRun: false
  config:
    controlPlaneEndpointIP: 192.168.105.111
    controlPlaneNumber: 1
    workersNumber: 0
    # clusterAnnotations:
    #   domain: ""
    # clusterLabels:
    #   app.kubernetes.io/knative: enabled
    #   app.kubernetes.io/addon: enabled
    controlPlane:
      image: ubuntu
      minCPU: 2
      minMemory: 8192
      resourcePool: ""
      tags: []
    worker:
      image: ubuntu
      minCPU: 2
      minMemory: 8192
      resourcePool: ""
      tags: []
    maas:
      dnsDomain: ""
    # preStartCommands:
    #   - update-ca-certificates
    customUserDataRef:
      secretRef:
        name: mscp-base-userdata
        key: value
    k0s:
      version: v1.35.4+k0s.0
      arch: arm64
      network:
        provider: custom
      api:
        extraArgs: {}
      cpArgs:
        - --enable-worker
        - --disable-components=konnectivity-server
        - --kubelet-extra-args="--fail-cgroupv1=false"
      workerArgs:
        - --kubelet-extra-args="--fail-cgroupv1=false"
  serviceSpec:
    services:
      - name: cilium
        namespace: kube-system
        template: cni-1-0-7
        values: |
          # FIXME: cilium
          cilium:
            enabled: true
            kubeProxyReplacement: true
            k8sServiceHost: ""
            k8sServicePort: 6443
            # ipv6:
            #   enabled: true
            operator:
              replicas: 1
            # hubble:
            #   relay:
            #     enabled: true
            #   ui:
            #     enabled: true
            # nodePort:
            #   addresses: []
            # bpf:
            #   hostLegacyRouting: true
            # bgp:
            #   enabled: true
            #   peer:
            #     authSecretRef: ""
            #     addressFamilies:
            #       - afi: ipv4
            #         safi: unicast
            #         advertisements:
            #           matchLabels:
            #             advertise: bgp
            #       - afi: ipv6
            #         safi: unicast
            #         advertisements:
            #           matchLabels:
            #             advertise: bgp
            #   instances:
            #     - name: frr
            #       localASN: 64512
            #       overrides:
            #         enabled: true
            #       peers:
            #         - name: frrv4
            #           peerASN: 64513
            #           peerAddress: ""
            #           peerConfigRef:
            #             name: bgp-peer-config
            #         - name: frrv6
            #           peerASN: 64513
            #           peerAddress: ""
            #           peerConfigRef:
            #             name: bgp-peer-config
            # pool:
            #   enabled: true
            #   blocks:
            #     - cidr: ""
            #     - cidr: ""
      - name: openebs
        namespace: kube-system
        template: csi-1-0-7
        # values: |
        #   openebs:
        #     openebs-crds:
        #       csi:
        #         volumeSnapshots:
        #           enabled: true
        #     lvm-localpv:
        #       lvmNode:
        #         kubeletDir: /var/lib/k0s/kubelet/
        #       class:
        #         volgroup: openebs-vg
        #     localpv-provisioner:
        #       hostpathClass:
        #         enabled: false
        #       localpv:
        #         enabled: false
        #     engines:
        #       local:
        #         lvm:
        #           enabled: true
