---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: knative
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/knative: enabled
  serviceSpec:
    priority: 100
    services:
      - template: knative-1-0-2
        name: knative-operator
        namespace: operators
        values: |

          version: v1.20.0
          resources:
            rabbitmq:
              enabled: false
          event:
            enabled: false
            sources:
              enabled: false
            backstage:
              enabled: false
          server:
            enabled: false
          operator:
            enabled: true
      # FIXME: knative domain & cluster issuer
      - template: knative-1-0-2
        name: knative
        namespace: knative
        values: |

          version: v1.20.0
          resources:
            rabbitmq:
              enabled: false
              brokers:
                - name: default-broker
                  config:
                    name: default-config
                    queueType: quorum
                    create: false
                  deadLetterSink:
                    ref:
                      apiVersion: serving.knative.dev/v1
                      kind: Service
                      name: event-display
              sources:
                - name: rabbitmq-source
                  exchangeName: eventing-rabbitmq-source
                  queueName: eventing-rabbitmq-source
                  sinkRef:
                    apiVersion: serving.knative.dev/v1
                    kind: Service
                    name: event-display
              clusterRef:
                name: rabbitmq
                vhost: /knative
          event:
            enabled: false
            defaultBrokerClass: MTChannelBasedBroker
            config:
              enabled: false
              channel:
                default-ch-config: |
                  clusterDefault:
                    apiVersion: messaging.knative.dev/v1beta1
                    kind: InMemoryChannel
                    spec:
                      delivery:
                        backoffDelay: PT0.5S
                        backoffPolicy: exponential
                        retry: 5
              broker:
                channel-template-spec: |
                  apiVersion: messaging.knative.dev/v1beta1
                  kind: InMemoryChannel
                  spec:
                    delivery:
                      backoffDelay: PT0.5S
                      backoffPolicy: exponential
                      retry: 5
            sources:
              enabled: false
              ceph: false
              github: false
              gitlab: false
              kafka: false
              natss: false
              rabbitmq: false
              redis: false
            backstage:
              enabled: false
              version: v1.20.0
          server:
            enabled: true
            domain: local
            replicas: 1
            security:
              enabled: false
              guard: false
            network:
              gatewayAPI:
                install: false
                version: v1.20.0
                external:
                  class: envoy-gateway
                  name: kube-system/http-gateway
                  service: kube-system/envoy-kube-system-http-gateway-3e72d172
                internal:
                  class: envoy-gateway
                  name: kube-system/http-gateway
                  service: kube-system/envoy-kube-system-http-gateway-3e72d172
              kourier:
                enabled: true
                service:
                  type: NodePort
            ingress:
              type: kourier
            certmanager:
              enabled: true
              issuerRef:
                clusterIssuer:
                  name: ca-issuer-self-signed
                localIssuer:
                  name: ca-issuer-self-signed
          operator:
            enabled: false
