# FIXME: update hard-coded values with cluster annotations
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-gateway
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  dependsOn: []
  serviceSpec:
    priority: 100
    provider:
      name: ksm-projectsveltos
      selfManagement: true
    services:
      - template: gateway-1-0-3
        name: gateway
        namespace: kube-system
        # dependsOn:
        #   - name: envoy
        #   - name: ca-issuer
        #     namespace: kcm-system
        values: |
          gateways:
            - name: http-gateway
              className: envoy
              listeners:
                - name: http
                  port: 80
                  protocol: HTTP
                  hostname: "*.sandbox.testplay.io"
                  allowedRoutes:
                    namespaces:
                      from: All
                    kinds:
                      - kind: HTTPRoute
                - name: https
                  port: 443
                  protocol: HTTPS
                  hostname: "*.sandbox.testplay.io"
                  allowedRoutes:
                    namespaces:
                      from: All
                    kinds:
                      - kind: HTTPRoute
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - name: https-gw-cert
                        issuer: ca-issuer
            - name: tls-gateway
              className: envoy
              listeners:
                - name: tls
                  port: 443
                  protocol: TLS
                  hostname: "*.sandbox.testplay.io"
                  allowedRoutes:
                    namespaces:
                      from: All
                    kinds:
                      - kind: TLSRoute
                  tls:
                    mode: Passthrough
      - template: gateway-1-0-3
        name: hubble-http-route
        namespace: kube-system
        # dependsOn:
        #   - name: envoy
        #   - name: gateway
        #   - name: ca-issuer
        #     namespace: kcm-system
        values: |
          gateways: []
          routes:
            - name: hubble
              kind: HTTPRoute
              hostnames:
                - hubble.sandbox.testplay.io
              rules:
                - backendRefs:
                  - name: hubble-ui
                    port: 80
                - filters:
                    - type: RequestRedirect
                      requestRedirect:
                        scheme: https
                        statusCode: 301
              gateways:
                - name: http-gateway
      - template: gateway-1-0-3
        name: kcm-http-route
        namespace: kcm-system
        # dependsOn:
        #   - name: envoy
        #   - name: gateway
        #     namespace: kube-system
        #   - name: ca-issuer
        #     namespace: kcm-system
        values: |
          gateways: []
          routes:
            - name: kcm
              kind: HTTPRoute
              hostnames:
                - console.sandbox.testplay.io
              rules:
                - backendRefs:
                  - name: kcm-k0rdent-ui
                    namespace: kcm-system
                    port: 3000
                - filters:
                    - type: RequestRedirect
                      requestRedirect:
                        scheme: https
                        statusCode: 301
              gateways:
                - name: http-gateway
                  namespace: kube-system
