---
# FIXME: update hard-coded values with cluster annotations
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-ca-issuer
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  serviceSpec:
    priority: 100
    provider:
      name: ksm-projectsveltos
      selfManagement: true
    services:
      - template: ca-1-0-4
        name: ca-issuer
        namespace: kcm-system
        # dependsOn:
        #   - name: envoy
        #     namespace: kube-system
        #   - name: vault
        #     namespace: sre
        values: |
          issuers:
            - name: ca-issuer-self-signed
              clustered: true
              selfSigned: true
              secret:
                create: false
            - name: ca-issuer
              certManagerNamespace: kcm-system
              clustered: true
              type: acme
              secret:
                create: false
                tsig: tsig-secret
              acme:
                email: kcm@testplay.io
                server: https://vault.sandbox.testplay.io/v1/sandbox/pki/acme/directory
                zones:
                  - sandbox.testplay.io
                provider:
                  type: rfc2136
                  nameserver: 192.168.105.103:53
                  tsigAlgorithm: HMACSHA256
                  tsigKeyName: certmanager
                  tsigSecretSecretRef:
                    name: tsig-secret
                    key: secret
