---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-ca-issuer
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  serviceSpec:
    priority: 100
    provider:
      name: ksm-projectsveltos
      selfManagement: true
    services:
      - template: ca-1-0-4
        name: ca-issuer
        namespace: kcm-system
        # dependsOn:
        #   - name: envoy
        #     namespace: kube-system
        #   - name: vault
        #     namespace: sre
        values: |
          issuers:
            - name: ca-issuer-self-signed
              clustered: true
              selfSigned: true
              secret:
                create: false
            # - name: ca-issuer
            #   clustered: true
            #   type: acme
            #   secret:
            #     create: false
            #     tsig: tsig-secret
            #   acme:
            #     email: kcm@testplay.io
            #     server: https://vault.testplay.io:8200/v1/kcm/pki/acme/directory
            #     zones:
            #       - kcm.testplay.io
            #     provider:
            #       type: rfc2136
            #       nameserver: 192.168.2.10:53
            #       tsigAlgorithm: HMACSHA256
            #       tsigKeyName: certmanager
            #       tsigSecretSecretRef:
            #         name: tsig-secret
            #         key: secret
