---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-monitoring
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  dependsOn: []
  serviceSpec:
    priority: 100
    provider:
      name: ksm-projectsveltos
      selfManagement: true
    services:
      # TODO: monitoring
      # - template: monitoring-4-3-1
      #   name: monitoring
      #   namespace: kube-system
      #   dependsOn: []
      #   values: ""
